# Generated by Django 3.2.3 on 2021-05-27 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ev', models.DateTimeField()),
                ('contenido', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id_ed', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_mod', models.DateTimeField()),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.calendario')),
            ],
        ),
    ]
