# Generated by Django 3.2.3 on 2021-05-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='contenido',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
