# Generated by Django 3.2.3 on 2021-06-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_calendario_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='fecha_cr',
            field=models.DateTimeField(default=10),
            preserve_default=False,
        ),
    ]
