# Generated by Django 3.2.3 on 2021-06-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_calendario_fecha_cr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='fecha_cr',
        ),
    ]
